=== onmyway133/conf-data/schema/edition.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "year": {
      "type": "integer",
      "minimum": 1970,
      "maximum": 2100
    },
    "url": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "startDate": {
      "type": "string",
      "format": "date",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
    },
    "endDate": {
      "type": "string",
      "format": "date",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
    },
    "city": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "enum": [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "VG",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CK",
        "CR",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "CD",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "CI",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "XK",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "CG",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "NL",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "VI",
        "UG",
        "UA",
        "AE",
        "GB",
        "US",
        "UM",
        "UY",
        "UZ",
        "VU",
        "VA",
        "VE",
        "VN",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW"
      ]
    },
    "lat": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "lng": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "topics": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "cfp": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "maxLength": 2048,
          "format": "uri",
          "pattern": "^https?://"
        },
        "deadline": {
          "type": "string",
          "format": "date",
          "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
        },
        "open": {
          "type": "boolean"
        }
      },
      "required": [
        "open"
      ],
      "additionalProperties": false
    },
    "bannerUrl": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "playlistUrl": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "twitter": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "bluesky": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "mastodon": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "source": {
      "type": "string",
      "minLength": 1
    },
    "speakers": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
      }
    },
    "talks": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slug": {
            "type": "string",
            "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
          },
          "title": {
            "type": "string",
            "minLength": 1
          },
          "speakers": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
            }
          },
          "youtubeUrl": {
            "type": "string",
            "maxLength": 2048,
            "format": "uri",
            "pattern": "^https?://"
          },
          "topics": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "required": [
          "slug",
          "title",
          "speakers"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "year",
    "url",
    "startDate",
    "endDate",
    "city",
    "country",
    "topics"
  ],
  "additionalProperties": false
}

=== onmyway133/conf-data/conferences/kcd-toronto/2026.json
{
  "name": "KCD Toronto 2026",
  "year": 2026,
  "url": "https://kcdtoronto.ca",
  "startDate": "2026-05-13",
  "endDate": "2026-05-13",
  "city": "Toronto",
  "country": "CA",
  "lat": 43.70643,
  "lng": -79.39864,
  "topics": [
    "Data/AI",
    "DevOps",
    "Open Source"
  ],
  "cfp": {
    "url": "https://sessionize.com/kcd-toronto-2026",
    "deadline": "2026-02-16",
    "open": false
  },
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/zurihac/2024.json
{
  "name": "ZuriHac 2024",
  "year": 2024,
  "url": "https://zfoh.ch/zurihac2024",
  "startDate": "2024-06-08",
  "endDate": "2024-06-10",
  "city": "Rapperswil-Jona",
  "country": "CH",
  "topics": [
    "Haskell",
    "Networking"
  ],
  "twitter": "https://x.com/zurihac",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/artificial-intelligence-for-geological-modelling-and-mapping/2024.json
{
  "name": "Artificial Intelligence for Geological Modelling and Mapping 2024",
  "year": 2024,
  "url": "https://www.eventbrite.co.uk/e/artificial-intelligence-for-geological-modelling-and-mapping-tickets-749228040237",
  "startDate": "2024-06-22",
  "endDate": "2024-06-23",
  "city": "Exeter",
  "country": "GB",
  "lat": 50.7236,
  "lng": -3.52751,
  "topics": [
    "Data/AI"
  ],
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/amplify/2024.json
{
  "name": "Amplify 2024",
  "year": 2024,
  "url": "https://amplify.abstracta.us",
  "startDate": "2024-08-19",
  "endDate": "2024-08-21",
  "city": "Tulsa, OK",
  "country": "US",
  "lat": 36.15398,
  "lng": -95.99277,
  "topics": [],
  "cfp": {
    "url": "https://forms.gle/CzJnAWkToPwBkt5Y9",
    "deadline": "2024-06-15",
    "open": false
  },
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/eurorust/2023.json
{
  "name": "EuroRust 2023",
  "year": 2023,
  "url": "https://eurorust.eu",
  "startDate": "2023-10-12",
  "endDate": "2023-10-13",
  "city": "Brussels",
  "country": "BE",
  "lat": 50.85045,
  "lng": 4.34878,
  "topics": [
    "Rust"
  ],
  "twitter": "https://x.com/euro_rust",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/devops-conference-london/2023.json
{
  "name": "DevOps Conference London 2023",
  "year": 2023,
  "url": "https://devopscon.io/london",
  "startDate": "2023-04-24",
  "endDate": "2023-04-27",
  "city": "London",
  "country": "GB",
  "lat": 51.50853,
  "lng": -0.12574,
  "topics": [
    "DevOps",
    "Performance",
    "Security"
  ],
  "twitter": "https://x.com/devops_con",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/voice-ai/2023.json
{
  "name": "VOICE & AI 2023",
  "year": 2023,
  "url": "https://www.voiceand.ai",
  "startDate": "2023-09-05",
  "endDate": "2023-09-07",
  "city": "Washington, DC",
  "country": "US",
  "lat": 38.89511,
  "lng": -77.03637,
  "topics": [
    "APIs",
    "Data/AI",
    "Networking"
  ],
  "twitter": "https://x.com/VOICEandAI",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/elixirconf/2021.json
{
  "name": "ElixirConf 2021",
  "year": 2021,
  "url": "https://2021.elixirconf.com",
  "startDate": "2021-10-12",
  "endDate": "2021-10-13",
  "city": "Austin, TX",
  "country": "US",
  "lat": 30.26715,
  "lng": -97.74306,
  "topics": [
    "Elixir"
  ],
  "twitter": "https://x.com/elixirconf",
  "source": "confs.tech"
}
