=== onmyway133/conf-data/schema/edition.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "year": {
      "type": "integer",
      "minimum": 1970,
      "maximum": 2100
    },
    "url": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "startDate": {
      "type": "string",
      "format": "date",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
    },
    "endDate": {
      "type": "string",
      "format": "date",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
    },
    "city": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "enum": [
        "AF",
        "AX",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "VG",
        "BN",
        "BG",
        "BF",
        "BI",
        "CV",
        "KH",
        "CM",
        "CA",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CK",
        "CR",
        "HR",
        "CU",
        "CW",
        "CY",
        "CZ",
        "CD",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "SZ",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "CI",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "XK",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "KP",
        "MK",
        "MP",
        "NO",
        "OM",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "CG",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SX",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "KR",
        "SS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "NL",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "VI",
        "UG",
        "UA",
        "AE",
        "GB",
        "US",
        "UM",
        "UY",
        "UZ",
        "VU",
        "VA",
        "VE",
        "VN",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW"
      ]
    },
    "lat": {
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "lng": {
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "topics": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "cfp": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "maxLength": 2048,
          "format": "uri",
          "pattern": "^https?://"
        },
        "deadline": {
          "type": "string",
          "format": "date",
          "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"
        },
        "open": {
          "type": "boolean"
        }
      },
      "required": [
        "open"
      ],
      "additionalProperties": false
    },
    "bannerUrl": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "playlistUrl": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "twitter": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "bluesky": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "mastodon": {
      "type": "string",
      "maxLength": 2048,
      "format": "uri",
      "pattern": "^https?://"
    },
    "source": {
      "type": "string",
      "minLength": 1
    },
    "speakers": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
      }
    },
    "talks": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slug": {
            "type": "string",
            "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
          },
          "title": {
            "type": "string",
            "minLength": 1
          },
          "speakers": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
            }
          },
          "youtubeUrl": {
            "type": "string",
            "maxLength": 2048,
            "format": "uri",
            "pattern": "^https?://"
          },
          "topics": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "required": [
          "slug",
          "title",
          "speakers"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "year",
    "url",
    "startDate",
    "endDate",
    "city",
    "country",
    "topics"
  ],
  "additionalProperties": false
}

=== onmyway133/conf-data/conferences/react-conf-armenia/2019.json
{
  "name": "React Conf Armenia 2019",
  "year": 2019,
  "url": "https://reactconf.am",
  "startDate": "2019-05-25",
  "endDate": "2019-05-25",
  "city": "Yerevan",
  "country": "AM",
  "lat": 40.17765,
  "lng": 44.5126,
  "topics": [
    "JavaScript"
  ],
  "cfp": {
    "url": "https://docs.google.com/forms/d/e/1FAIpQLSeGedK-IMZ7HQMLaqBdO4cOTmShfKtap_JvqXZdIRDUWFf8NA/closedform",
    "deadline": "2019-04-10",
    "open": false
  },
  "twitter": "https://x.com/ReactConfAM",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/build-stuff/2019-2.json
{
  "name": "Build Stuff 2019",
  "year": 2019,
  "url": "https://www.ukraine.buildstuff.events",
  "startDate": "2019-11-18",
  "endDate": "2019-11-20",
  "city": "Kyiv",
  "country": "UA",
  "lat": 50.45466,
  "lng": 30.5238,
  "topics": [],
  "twitter": "https://x.com/Buildstuffua",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/devopsdays-columbus/2019.json
{
  "name": "DevOpsDays Columbus 2019",
  "year": 2019,
  "url": "https://devopsdays.org/events/2019-columbus/welcome",
  "startDate": "2019-09-18",
  "endDate": "2019-09-19",
  "city": "Columbus, OH",
  "country": "US",
  "lat": 39.96118,
  "lng": -82.99879,
  "topics": [
    "DevOps"
  ],
  "twitter": "https://x.com/DevOpsDaysOhio",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/visual-studio-live/2019.json
{
  "name": "Visual Studio Live! 2019",
  "year": 2019,
  "url": "https://vslive.com/events/las-vegas-2019/home.aspx",
  "startDate": "2019-03-03",
  "endDate": "2019-03-08",
  "city": "Las Vegas, NV",
  "country": "US",
  "lat": 36.17497,
  "lng": -115.13722,
  "topics": [],
  "cfp": {
    "url": "https://vslive.com/pages/call-for-papers.aspx",
    "open": false
  },
  "twitter": "https://x.com/VSLive",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/international-conference-on-data-mining-and-software-engineering/2020.json
{
  "name": "International Conference on Data Mining and Software Engineering 2020",
  "year": 2020,
  "url": "https://dmse2020.org",
  "startDate": "2020-09-26",
  "endDate": "2020-09-27",
  "city": "Copenhagen",
  "country": "DK",
  "lat": 55.67594,
  "lng": 12.56553,
  "topics": [
    "Data/AI"
  ],
  "cfp": {
    "url": "https://dmse2020.org/submission.html",
    "deadline": "2020-08-28",
    "open": false
  },
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/celosphere/2023.json
{
  "name": "Celosphere 2023",
  "year": 2023,
  "url": "https://www.celonis.com/celosphere",
  "startDate": "2023-11-14",
  "endDate": "2023-11-15",
  "city": "Munich",
  "country": "DE",
  "lat": 48.13743,
  "lng": 11.57549,
  "topics": [
    "Data/AI"
  ],
  "twitter": "https://x.com/Celonis",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/soss-policy-summit/2024.json
{
  "name": "SOSS Policy Summit 2024",
  "year": 2024,
  "url": "https://events.linuxfoundation.org/soss-policy-summit-dc",
  "startDate": "2024-09-09",
  "endDate": "2024-09-09",
  "city": "Washington, DC",
  "country": "US",
  "lat": 38.89511,
  "lng": -77.03637,
  "topics": [
    "Security"
  ],
  "twitter": "https://x.com/openssf",
  "source": "confs.tech"
}

=== onmyway133/conf-data/conferences/javazone/2022.json
{
  "name": "JavaZone 2022",
  "year": 2022,
  "url": "https://2022.javazone.no",
  "startDate": "2022-09-07",
  "endDate": "2022-09-08",
  "city": "Oslo",
  "country": "NO",
  "lat": 59.91273,
  "lng": 10.74609,
  "topics": [
    "Java"
  ],
  "cfp": {
    "url": "https://2022.javazone.no/#/speakers",
    "deadline": "2022-04-30",
    "open": false
  },
  "twitter": "https://x.com/javazone",
  "source": "confs.tech"
}
